-- Clients Who Have Made Payments Greater Than 10,000 

SELECT * FROM clients 
WHERE id IN (
    SELECT client_id FROM payments 
    WHERE amount > 10000
);

-- Total Payments Made by Each Client
SELECT c.id, c.name, c.email, 
       (SELECT SUM(amount) FROM payments p WHERE p.client_id = c.id) AS total_paid 
FROM clients c;

-- All Packages with Location and Assigned Guide Details
SELECT tp.package_id, tp.name AS package_name, tp.price, l.name AS location_name, g.name AS guide_name
FROM travel_packages tp
JOIN locations l ON tp.location_id = l.location_id
JOIN guides g ON tp.guide_id = g.guide_id;


-- All Bookings Along With Client and Package Details
SELECT b.booking_id, c.name AS client_name, p.name AS package_name, p.price, b.createdAt 
FROM bookings b
JOIN clients c ON b.client_id = c.id
JOIN travel_packages p ON b.package_id = p.package_id;

-- Packages That Have Not Been Booked Yet
SELECT * FROM travel_packages 
WHERE package_id NOT IN (SELECT DISTINCT package_id FROM bookings);

-- Total Revenue Generated from Each Tour Package  
SELECT p.package_id, p.name, SUM(payments.amount) AS total_revenue 
FROM payments 
JOIN bookings b ON payments.booking_id = b.booking_id
JOIN travel_packages p ON b.package_id = p.package_id
GROUP BY p.package_id, p.name;

-- Most Popular Travel Package (Based on Bookings)
 SELECT p.package_id, p.name, COUNT(*) AS total_bookings
FROM bookings b
JOIN travel_packages p ON b.package_id = p.package_id
GROUP BY p.package_id, p.name
ORDER BY total_bookings DESC
LIMIT 1;

-- Most Popular Destination Based on Bookings 
SELECT l.location_id, l.name AS location_name, COUNT(*) AS total_bookings
FROM bookings b
JOIN travel_packages tp ON b.package_id = tp.package_id
JOIN locations l ON tp.location_id = l.location_id
GROUP BY l.location_id, l.name
ORDER BY total_bookings DESC
LIMIT 1;

-- Total Revenue Generated by Each Guide’s Assigned Packages
SELECT g.guide_id, g.name AS guide_name, SUM(pay.amount) AS total_revenue
FROM guides g
JOIN travel_packages tp ON g.guide_id = tp.guide_id
JOIN bookings b ON tp.package_id = b.package_id
JOIN payments pay ON b.booking_id = pay.booking_id
GROUP BY g.guide_id, g.name;

-- Clients Who Have Booked a Package in a Specific Location
SELECT DISTINCT c.name AS client_name, c.email, l.name AS location_name
FROM bookings b
JOIN clients c ON b.client_id = c.id
JOIN travel_packages p ON b.package_id = p.package_id
JOIN locations l ON p.location_id = l.location_id
WHERE l.name = 'Cox\'s Bazar';














